moodboard/urls.py
from django.urls import path
from . import views
from .views import PostView, PostDetailView, CreatePostView, UpdatePostView, DeletePostView, CreateCommentView

urlpatterns = [
    path('', PostView.as_view(), name="moodboard-home" ),
    path('post/<int:pk>/', PostDetailView.as_view(), name="post-detail"),
    path('post/<int:pk>/update/', UpdatePostView.as_view(), name="post-update"),
    path('post/<int:pk>/delete/', DeletePostView.as_view(), name="post-delete"),
    path('post/new/', CreatePostView.as_view(), name="post-create"),
    path('post/<int:pk>/comment/', CreateCommentView.as_view(), name="post-comment"),
    path('about/', views.about, name="moodboard-about" ),
    path('search_posts/', views.PostsSearchView.as_view(), name="search_posts"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

# Routing 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('profile/', user_views.profile, name="profile"),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path('',include('moodboard.urls')),
]

moodboard/models.py
from django.db import models
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse



# Post model
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now)
    sentiment = models.CharField(max_length=10, blank=True, null=True)
 
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.pk})
    

# Comment Model
class Comment(models.Model):
    # Foreign key to post
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now)
    sentiment = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f'{self.author}\'s comment on {self.post}'

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk':self.post.pk})
    
    

moodboard/forms.py
from .models import Post, Comment
from django import forms

# Comment form

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields  = ('author', 'text',)
        

moodboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Post, Comment
from .forms import CommentForm
import requests
from django.shortcuts import render, redirect, reverse
import pickle
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)


# code references
# https://docs.djangoproject.com/en/4.2/topics/class-based-views/generic-editing/
# https://docs.djangoproject.com/en/4.2/ref/class-based-views/generic-display/



def home(request):
    posts = {
        'posts': Post.objects.all()
    }
    return render(request, 'moodboard/home.html',posts)

class PostView(ListView):
    model = Post

    # <app>/<model>_<viewtype>.html
    template_name = 'moodboard/home.html'
    context_object_name = 'posts'

    # Change order
    ordering = ['-published_date']


class PostDetailView(DetailView):
    model = Post

    form = CommentForm

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            post = self.get_object()
            form.instance.user = request.user
    

    # Calculate the overall sentiment of the comments on the post
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        comments = Comment.objects.filter(post=self.object)


        # Count the postive and negative comments
        pos =0
        neg =0
        comment_count = 0

        for comment in comments:
            comment_count +=1
            sentiment = comment.sentiment
            print(sentiment)
            if sentiment == 'Negative':
                neg+=1
            if sentiment == 'Positive':
                pos+=1
        
        print(pos)
        print(neg)


        # Percentage of postive comments
        if comment_count > 0:
            pos_percentage = (pos / comment_count) * 100
        
        else: 
            pos_percentage = 0
        
        print(pos_percentage)
        if pos_percentage >= 90:
            average_sentiment = 'Overwhemingly Positive'
        elif pos_percentage >= 70:
            average_sentiment = 'Positive'
        elif pos_percentage >= 50:
            average_sentiment = 'Mixed'
        elif pos_percentage >= 30:
            average_sentiment = 'Negative'
        else:
            average_sentiment = 'Overwhemingly negative'


        context['comments'] = comments
        context['post'] = self.object

        context['average_sentiment'] = average_sentiment

        
        



        return context



        
    

   

class PostsSearchView(ListView):
    model = Post
    template_name = 'moodboard/search_results.html'
    context_object_name = 'posts'

    def get_queryset(self):
        query = self.request.GET.get('q', '')
        return Post.objects.filter(title__icontains=query).order_by('-published_date')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = self.get_queryset()

        pos = 0
        neg = 0
        post_count = 0

        for post in posts:
            post_count += 1
            sentiment = post.sentiment
            if sentiment == 'Negative':
                neg += 1
            if sentiment == 'Positive':
                pos += 1

        if post_count > 0:
            pos_percentage = (pos / post_count) * 100
        else:
            pos_percentage = 0

        if pos_percentage >= 90:
            average_sentiment = 'Overwhelmingly Positive'
        elif pos_percentage >= 70:
            average_sentiment = 'Positive'
        elif pos_percentage >= 50:
            average_sentiment = 'Mixed'
        elif pos_percentage >= 30:
            average_sentiment = 'Negative'
        else:
            average_sentiment = 'Overwhelmingly Negative'

        context['posts'] = posts
        context['average_sentiment'] = average_sentiment
        search_term = self.request.GET.get('q')
        context['average_sentiment_title'] = f"Overall Sentiment of Posts Containing '{search_term}'"

        return context




     
     
    
    
    


from django.shortcuts import get_object_or_404

class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'text']

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.published_date = timezone.now()
        response = super().form_valid(form)

        # Get the primary key of the created post
        post_pk = self.object.pk

        post_text = form.cleaned_data['text']

        # Analyze the sentiment of the post text
        sentiment = analyze_sentiment(post_text)

        # Update the sentiment of the created post
        post = Post.objects.get(pk=post_pk)
        post.sentiment = sentiment
        post.save()

        return response


class CreateCommentView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['text']
    template_name = 'moodboard/add_comment.html'
    success_url = '/'


    def form_valid(self, form):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        form.instance.author = self.request.user
        form.instance.post = post
        response = super().form_valid(form)

       
        comment_pk = self.object.pk

       
        post_text = form.cleaned_data['text']

        # Analyze the sentiment of the post text
        sentiment = analyze_sentiment(post_text)

        
        comment = Comment.objects.get(pk=comment_pk)
        comment.sentiment = sentiment
        comment.save()

        return response
    
    def get_success_url(self):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return post.get_absolute_url()

    




class UpdatePostView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post

    # Establish form fields
    fields = ['title', 'text']


    # Override form valid method
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    

class  DeletePostView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False




def about(request):
    return render(request, 'moodboard/about/')

    
# References 

# https://ccbv.co.uk/

# Load the pickled sentiment analysis model and vectorizer
with open('C:\\Users\\harry\\Desktop\\final_year_project\\moodboard\\sentiment_analysis_files\\Sentiment-LR.pickle', 'rb') as f:
    model = pickle.load(f)

with open('C:\\Users\\harry\\Desktop\\final_year_project\\moodboard\\sentiment_analysis_files\\vectorizer-ngram-(1,2).pickle', 'rb') as f:
    vectorizer = pickle.load(f)

def analyze_sentiment(text):
 

    # Clean data
    text = text.lower()  
    text = text.replace('\n', ' ')  
    text = text.replace('\r', ' ')
    text = text.replace('\t', ' ')
    text = text.strip()  

   # Vectorize
    feature_vector = vectorizer.transform([text])

   # Predict sentiment
    predicted_sentiment = model.predict(feature_vector)[0]

    if predicted_sentiment == 1:
        return 'Positive'
    else:
        return 'Negative'

moodboard/templates/moodboard/about.html
{% extends "moodboard/base.html" %}
{% block content %}
    <h1> About page</h1>

{% endblock content %}

moodboard/templates/moodboard/add_comment.html
{% extends "moodboard/base.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST" action="{% url 'post-comment' pk=post.pk %}">
            {% csrf_token %}
            <fieldset class="form-group ">
                <legend class="border-bottom mb-4">Add comment</legend>
                {{ form|crispy}}
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>  
        
    </div>
{% endblock content %}

moodboard/templates/moodboard/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'moodboard/main.css' %}">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Pacifico">
    
    {% if title %}
        <title>MoodBoard - {{ title }}</title>
    {% else %}
        <title>MoodBoard</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'moodboard-home' %}">MoodBoard</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'moodboard-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'moodboard-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

              <!--If the user is already logged in only show the logout button-->
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>


              {% else %}
                <!--If the user is not logged in show the login and register links-->
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>


            {% endfor %}

          {% endif %}
          {% block content %}{% endblock %}
        </div>
        
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

moodboard/templates/moodboard/home.html
{% extends "moodboard/base.html" %}
{% load static %}
{% block content %}

<form action="{% url 'search_posts' %}" method="get">
    
    <input type="text" class="form-control" name="q" value="" placeholder="Search for post...">
   
</form>
<br>
</br>

  <div class="mb-3 input-group border border-4 rounded">
        <a href="{% url 'post-create' %}" class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">{{ user.username }}</span>
            </div>
            <input type="text" class="form-control" placeholder="Create a new post...">
            
        </a>
    </div>
    {% for post in posts %}
        <article class="media content-section shadow-lg p-3 mb-5 bg-white rounded ">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.published_date }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.text }}</p>
            <p class="article-sentiment">Sentiment: {{ post.sentiment }}</p>

            {% if post.sentiment == 'Positive' %}
                <div style="position: relative;">
                    <img src="{% static 'moodboard/pictures/happyface.png' %}" style="position: absolute; bottom: 0; right: 0; width: 50px; height: 50px;">
                </div>
            {% elif post.sentiment == 'Negative' %}
                <div style="position: relative;">
                    <img src="{% static 'moodboard/pictures/sadface.png' %}" style="position: absolute; bottom: 0; right: 0; width: 50px; height: 50px;">
                </div>
            {% endif %}
            
          </div>
        </article>
    {% endfor %}
{% endblock content %}

moodboard/templates/moodboard/post_confirm_delete.html
{% extends "moodboard/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

moodboard/templates/moodboard/post_detail.html
{% extends "moodboard/base.html" %}
{% load static %}
{% block content %}
   
   
    <article class="media content-section shadow-lg p-3 mb-5 bg-white rounded ">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.author }}</a>
            <small class="text-muted">{{ object.published_date }}</small>
        </div>
        <!--If the current logged in user matches show edit and delete buttons-->
        {% if object.author == user %}
            <a href ="{% url 'post-update' object.id %}">Edit</a>
            <a href ="{% url 'post-delete' object.id %}">Delete</a>


        {% endif %}

        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.text }}</p>
        <p class="article-sentiment">Sentiment: {{ object.sentiment }}</p>

        {% if object.sentiment == 'Positive' %}
          <div style="position: relative;">
              <img src="{% static 'moodboard/pictures/happyface.png' %}" style="position: absolute; bottom: 0; right: 10px; width: 50px; height: 50px;">
          </div>
        {% elif object.sentiment == 'Negative' %}
          <div style="position: relative;">
              <img src="{% static 'moodboard/pictures/sadface.png' %}" style="position: absolute; bottom: 0; right: 10px; width: 50px; height: 50px;">
          </div>
        {% endif %}


        
 
        
        
        </div>


        
    </article>


    <h2>Comments</h2>

    <h2>{{ average_sentiment }}</h2>
  

    <form method="post" action="{% url 'post-comment' pk=post.pk %}">
      {% csrf_token %}
      <div>
        <label for="id_text">Comment:</label>
        <textarea id="id_text" name="text"></textarea>
      </div>
      <button type="submit">Submit</button>
    </form>


      {% for comment in object.comments.all %}
        <br>
        <p>
          {{ comment.author }}
          {{ comment.published_date }}
          {{ comment.text }}
          {% if comment.sentiment == 'Positive' %}
            <div style="position: relative;">
                <img src="{% static 'moodboard/pictures/happyface.png' %}" style="position: absolute; bottom: 0; right: 20px; width: 50px; height: 50px;">
            </div>
        {% elif comment.sentiment == 'Negative' %}
            <div style="position: relative;">
                <img src="{% static 'moodboard/pictures/sadface.png' %}" style="position: absolute; bottom: 0; right: 20px; width: 50px; height: 50px;">
            </div>
        {% endif %}
        </p>
      {% endfor %}
   





    
    

</div>
    
    
{% endblock content %}

moodboard/templates/moodboard/post_form.html
{% extends "moodboard/base.html" %}
{% load static%}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group ">
                <legend class="border-bottom mb-4">Create Post</legend>
                {{ form|crispy}}
            </fieldset>
            <div class="form-group text-center">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>  
        
    </div>
{% endblock content %}

moodboard/templates/moodboard/search_results.html
{% extends "moodboard/base.html" %}
{% load static %}
{% block content %}

<h2>{{ average_sentiment_title }}: {{ average_sentiment }}</h2>


   {% for post in posts %}
    <article class="media content-section shadow-lg p-3 mb-5 bg-white rounded">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author }}</a>
            <small class="text-muted">{{ post.published_date }}</small>
        </div>
        <!--If the current logged-in user matches, show edit and delete buttons-->
        {% if post.author == user %}
            <a href="{% url 'post-update' post.pk %}">Edit</a>
            <a href="{% url 'post-delete' post.pk %}">Delete</a>
        {% endif %}

        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.text }}</p>
        <p class="article-sentiment">Sentiment: {{ post.sentiment }}</p>

        {% if post.sentiment == 'Positive' %}
          <div style="position: relative;">
              <img src="{% static 'moodboard/pictures/happyface.png' %}" style="position: absolute; bottom: 0; right: 10px; width: 50px; height: 50px;">
          </div>
        {% elif post.sentiment == 'Negative' %}
          <div style="position: relative;">
              <img src="{% static 'moodboard/pictures/sadface.png' %}" style="position: absolute; bottom: 0; right: 10px; width: 50px; height: 50px;">
          </div>
        {% endif %}
        
        </div>
        
    </article>
   {% empty %}
    <p>No posts found.</p>
   {% endfor %}

   

{% endblock content %}